from fastapi import APIRouter, Depends, HTTPException, UploadFile, File
from sqlalchemy.orm import Session
from typing import List
from uuid import UUID
from database import get_db
from models import Document, DocumentChunk
from schemas import DocumentResponse
import aiofiles
import os

router = APIRouter()

@router.post("/upload", response_model=DocumentResponse, status_code=201)
async def upload_document(file: UploadFile = File(...), db: Session = Depends(get_db)):
    """Upload a document to the vector store"""
    # Verify file type
    file_ext = file.filename.split('.')[-1].lower()
    if file_ext not in ['txt', 'pdf']:
        raise HTTPException(status_code=400, detail="Only .txt and .pdf files are supported")
    
    # Read file content
    content = await file.read()
    
    # Extract text based on file type
    if file_ext == 'txt':
        text_content = content.decode('utf-8')
    elif file_ext == 'pdf':
        # PDF processing will be implemented with the AI assistant
        # For now, just store a placeholder
        text_content = "PDF processing to be implemented"
    
    # Create document record
    db_document = Document(
        filename=file.filename,
        file_type=file_ext,
        content=text_content,
        summary=None  # Will be generated by LLM
    )
    
    db.add(db_document)
    db.commit()
    db.refresh(db_document)
    
    return db_document

@router.get("", response_model=List[DocumentResponse])
def list_documents(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    """List all documents"""
    documents = db.query(Document).offset(skip).limit(limit).all()
    return documents

@router.get("/{document_id}", response_model=DocumentResponse)
def get_document(document_id: UUID, db: Session = Depends(get_db)):
    """Get a specific document"""
    document = db.query(Document).filter(Document.id == document_id).first()
    if not document:
        raise HTTPException(status_code=404, detail="Document not found")
    return document

@router.delete("/{document_id}", status_code=204)
def delete_document(document_id: UUID, db: Session = Depends(get_db)):
    """Delete a document and its chunks"""
    db_document = db.query(Document).filter(Document.id == document_id).first()
    if not db_document:
        raise HTTPException(status_code=404, detail="Document not found")
    
    db.delete(db_document)
    db.commit()
    return None

